### ISSUE TITLE
Can't write welcome text to screen (step 41 - 42)

### ISSUE THREAD

**Issue by kode-tar-gz** [yjerem/kilo-tutorial#57]
I've been slowly following this tutorial for a few days. hadn't had at major problems until now: I can't get the welcome message (editor name and version) to show up. My `editorDrawRows()` function (named `voided_draw_rows()` in my code) and `editorRefreshScreen()` (`voided_refresh_screen()`) are pretty much exactly the same as in the tutorial, so I don't know what's causing this. My code is in my [voided repo.](https://github.com/Kode-Kun/voided)

**Comment by kode-tar-gz** [comment]
ok i figured something out, but I still can't get rid of the bug: the row count is completely wrong, double what its supposed to be, and the `editorRefreshScreen()` function isn't actually clearing the screen. whenever i give the program some input, it re-prints the entire screen, scrolling the terminal down and just writing the new screen under the old one. I don't know what's causing this.

**Comment by paigeruten** [comment]
Hi! Looks like you just have your `E.sccols` and `E.scrows` reversed on line 188 :)
